version: "2"
services:
  #data
  data:
    image: busybox
  # mysql
  mysql:
    image: mysql
    volumes:
      - /vagrant/docker/mysql/volume/sql:/docker-entrypoint-initdb.d:rw
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  # php
  app:
    image: php:7.0-fpm
    ports:
      - "9000:9000"
    container_name: docker-app
    depends_on:
      - mysql
    links:
      - mysql:mysql
  # reverse-proxy
  proxy:
    build: proxy
    links:
      - app:app
    ports:
      - "80:80"
    volumes:
      - /vagrant/docker/proxy/volume:/volume:rw
